name: CI

on: 
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Ada mone ith undo?!
    - name: Run a multi-line script
      run: python main.py waka.json
